apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: mysql-service
        - name: PMA_PORT
          value: "3306"
        - name: PMA_ARBITRARY
          value: "1"
        ports:
        - containerPort: 80
          name: phpmyadmin
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 1024Mi  
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
