apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-nfs-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: apache-nfs
  mountOptions:
    - nfsvers=4.1
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.24   
    path: /nfsdrive/apache_crud # Replace with your NFS share path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-nfs-pvc
spec:
  storageClassName: apache-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
