apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-nfs-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: mysql-nfs
  mountOptions:
    - nfsvers=4.1
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.24   
    path: /nfsdrive/mysql # Replace with your NFS share path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-nfs-pvc
spec:
  storageClassName: mysql-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
