apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MTIzNDU2Nzg=
  MYSQL_DATABASE: ZGVtb2Ri
  MYSQL_USER: ZGVtb3VzZXI=
  MYSQL_PASSWORD: MTIzNDU2Nzg=
